import ApolloContextProvider from "@/components/contextProviders/ApolloContextProvider";
import AuthContextProvider from "@/components/contextProviders/AuthContextProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider session={session}>
          <ApolloContextProvider>{children}</ApolloContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
